# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85b43bc3bb9c96276dbec5d5866ddc4c0dd449369cba73189cc1d63295377494a4110827022631f05137c39a9a37e6d760c7ce46fa2f064997b42cea6b3bf406

test:
  secret_key_base: 43b8b2e107acb004ddcb7b8c1b66bcce2d4c5b78dc68163440d39e05b6f96746d47112ff512e75e94a06ed0270314f48486ce587cc572ea5cf56f88fd6f905a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
